Repository 2024-Summer-Bootcamp-TeamJ/Backend, pull requests merged in 2024-07, with the labels that each got.

#16 Feat/#14 유저 닉네임 수정 기능 구현
  app/crud/user.py
  app/routers.py
  app/schemas.py
Labels: ✨Feat

#17 Feat/#15 시간대 변경 UTC -> KST
  app/models.py
  requirements.txt
Labels: ❤️‍🔥BugFix

#25 Dev 0711 개발 완료된 api 적용
  .gitignore
  Dockerfile
  README.md
  app/crud/chatroom.py
  app/crud/mentor.py
  app/crud/prescription.py
  app/crud/user.py
  app/database.py
  app/main.py
  app/models.py
  app/routers.py
  app/schemas.py
  app/settings.py
  app/templates/index.html
  docker-compose.yml
  requirements.txt
Labels: ✨Feat

#43 Dev 0712 RabbitMQ, Celery 추가
  Dockerfile.worker
  app/crud/chat.py
  app/database.py
  app/routers/chat.py
  app/routers/chatroom.py
  app/schemas.py
  app/settings.py
  app/utils/celery_worker.py
  docker-compose.yml
  requirements.txt
  requirements.worker.txt
Labels: 🌎Deploy

#44 [feat] GPT와 연동
  app/routers/chat.py
  app/utils/celery_worker.py
  docker-compose.yml
  requirements.txt
  requirements.worker.txt
Labels: ✨Feat

#54 Feat/#53
  app/crud/chat.py
  app/crud/chatroom.py
  app/crud/mentor.py
  app/crud/prescription.py
  app/crud/user.py
  app/database.py
  app/routers/chat.py
  app/routers/chatroom.py
  app/routers/mentor.py
  app/routers/prescription.py
  app/routers/user.py
Labels: 🔨Refactor

#49 Dev
  app/crud/chat.py
  app/crud/chatroom.py
  app/crud/mentor.py
  app/crud/prescription.py
  app/crud/user.py
  app/database.py
  app/main.py
  app/routers/chat.py
  app/routers/chatroom.py
  app/routers/mentor.py
  app/routers/prescription.py
  app/routers/user.py
  app/schemas.py
  app/templates/index.html
  docker-compose.yml
Labels: 🌎Deploy

#63 Dev 0717 GPT, 음성, RAG 연동
  .github/ISSUE_TEMPLATE/test.md
  app/crud/chat.py
  app/routers/chat.py
  app/routers/chatroom.py
  app/templates/index.html
  app/utils/celery_worker.py
  app/utils/opensearch.py
  docker-compose.yml
  requirements.txt
  requirements.worker.txt
Labels: 🌎Deploy

#74 Refactor/#73 - chat.py 리팩토링
  app/crud/chat.py
  app/routers/chat.py
  app/utils/opensearch.py
Labels: 🔨Refactor

#77 [feat] opensearch 검색 개선
  app/utils/opensearch.py
Labels: ✨Feat

#78 Test/#58 - crud 함수 단위 테스트 코드 추가
  app/tests/test_base.py
  app/tests/test_crud_chatroom.py
  app/tests/test_crud_mentor.py
  app/tests/test_crud_prescription.py
  app/tests/test_crud_user.py
Labels: 🧪Test

#81 Feat/#76 : 채팅 내용을 요약해서 처방전 만드는 기능 구현
  app/routers/chat.py
  app/utils/gpt.py
Labels: ✨Feat

#86 Test/#85
  .github/workflows/run-pytest.yml
  app/models.py
  app/schemas.py
  requirements.txt
Labels: 🧪Test

#90 Refactor/#84 불필요한 라이브러리 정리
  app/utils/celery_worker.py
  requirements.txt
  requirements.worker.txt
Labels: 🔨Refactor

#96 Test/#92 routers/ 내부에 있는 함수 단위 테스트 적용
  app/database.py
  app/tests/test_00_base.py
  app/tests/test_base.py
  app/tests/test_crud_chat.py
  app/tests/test_crud_chatroom.py
  app/tests/test_crud_mentor.py
  app/tests/test_crud_prescription.py
  app/tests/test_crud_user.py
  app/tests/test_router_chatroom.py
  app/tests/test_router_mentor.py
  app/tests/test_router_prescription.py
  app/tests/test_router_user.py
Labels: 🧪Test

#100 Feat/#99 처방전 방식에서 편지 방식으로 변경
  app/routers/chat.py
Labels: ✨Feat

#101 Feat/#93 Nginx 적용
  app/main.py
  app/routers/root.py
  app/templates/index.html
  docker-compose.yml
  nginx.conf
Labels: ✨Feat

#95 Dev 0719 목소리 재적용, 프롬프트 개선
  Dockerfile
  Dockerfile.worker
  app/database.py
  app/main.py
  app/routers/chat.py
  app/routers/chatroom.py
  app/routers/root.py
  app/templates/index.html
  app/tests/test_00_base.py
  app/tests/test_base.py
  app/tests/test_crud_chat.py
  app/tests/test_crud_chatroom.py
  app/tests/test_crud_mentor.py
  app/tests/test_crud_prescription.py
  app/tests/test_crud_user.py
  app/tests/test_router_chatroom.py
  app/tests/test_router_mentor.py
  app/tests/test_router_prescription.py
  app/tests/test_router_user.py
  app/utils/celery_worker.py
  app/utils/gpt.py
  app/utils/opensearch.py
  docker-compose.yml
  nginx.conf
  requirements.txt
  requirements.worker.txt
Labels: 🌎Deploy

#112 Dev 0722 프롬프트 개선
  Dockerfile
  app/crud/chat.py
  app/crud/chatroom.py
  app/crud/mentor.py
  app/crud/prescription.py
  app/crud/user.py
  app/log.ini
  app/routers/chat.py
  app/routers/chatroom.py
  app/routers/mentor.py
  app/routers/prescription.py
  app/routers/user.py
  app/tests/test_router_mentor.py
  app/utils/gpt.py
  app/utils/opensearch.py
  docker-compose.yml
Labels: 🌎Deploy

#121 Dev 0723 Prometheus, grafana 추가
  .github/workflows/run-pytest.yml
  .gitignore
  app/crud/prescription.py
  app/database.py
  app/formatter.py
  app/log_config.py
  app/main.py
  app/routers/chat.py
  app/routers/mentor.py
  app/tests/conftest.py
  app/tests/test_00_base.py
  app/tests/test_api_user.py
  docker-compose.yml
  prometheus/prometheus.yml
  requirements.txt
Labels: 🌎Deploy

#125 feat: CORS에 배포된 프론트 주소 추가
  app/main.py
Labels: ✨Feat

#126 Dev 0724 CORS 추가
  app/main.py
Labels: 🌎Deploy

#129 feat: grafana를 nginx와 연결
  docker-compose.yml
  nginx.conf
Labels: ✨Feat

#132 Feat/#130 grafana endpoint "/" -> "/monitoring"으로 수정
  docker-compose.yml
  nginx.conf
Labels: ✨Feat

#133 Feat/#122 HTTPS 적용, docker-compose 배포환경 분리
  .gitignore
  app/main.py
  app/tests/test_api_chatroom.py
  app/tests/test_api_mentor.py
  app/tests/test_api_prescription.py
  app/tests/test_api_user.py
  docker-compose.prod.yml
  docker-compose.yml
  nginx.conf
  run_prod.sh
Labels: ✨Feat

#134 Dev 0725 모니터링 툴 적용, 테스트 추가, https 적용
  .gitignore
  Dockerfile.flower
  alertmanager/alertmanager.yml.tmpl
  alertmanager/entrypoint.sh
  app/main.py
  app/routers/prescription.py
  app/schemas.py
  app/tests/test_api_chatroom.py
  app/tests/test_api_mentor.py
  app/tests/test_api_prescription.py
  app/tests/test_api_user.py
  docker-compose.prod.yml
  docker-compose.yml
  mysql-exporter/my-config.conf
  nginx.conf
  prometheus/alert-rules.yml
  prometheus/prometheus.yml
  run_prod.sh
Labels: 🌎Deploy

#136 Fix/#135 배포 간 발생한 오류 수정
  docker-compose.prod.yml
  nginx.conf
Labels: ❤️‍🔥BugFix

#141 Dev 0725 배포 환경에서 rds 적용
  docker-compose.prod.yml
  mysql-exporter/my-config.conf
Labels: 🌎Deploy

#146 [feat]swagger 아이디,비밀번호 설정
  .github/workflows/run-pytest.yml
  app/main.py
  app/routers/root.py
  docker-compose.prod.yml
  docker-compose.yml
Labels: ✨Feat

#147 Dev 0726 swagger 문서 암호화, 통합 테스트 리팩토링
  .github/workflows/run-pytest.yml
  app/main.py
  app/routers/root.py
  app/tests/conftest.py
  app/tests/test_api_chatroom.py
  app/tests/test_api_mentor.py
  app/tests/test_api_prescription.py
  app/tests/test_api_user.py
  docker-compose.prod.yml
  docker-compose.yml
  prometheus/prometheus.yml
Labels: 🌎Deploy

#156 Refactor/#149 GPT 예외처리 추가, 로깅 개선
  app/routers/chat.py
  app/templates/index.html
  app/utils/opensearch.py
Labels: 🔨Refactor

#151 [feat] ec2에 자동으로 배포하는CD 파이프라인 구축
  .github/workflows/run-production.yml
Labels: 🌎Deploy

#159 Dev 0726 로그 레벨 환경변수 적용
  app/formatter.py
  app/log_config.py
  docker-compose.prod.yml
  docker-compose.yml
Labels: 🌎Deploy

#161 refactor: opensearch 예외 처리
  app/routers/chat.py
Labels: 🔨Refactor

#162 Dev 0729 opensearch 예외 처리
  app/routers/chat.py
Labels: 🌎Deploy
